# -*- coding: utf-8 -*-
"""
Created on Sat Aug  1 17:38:36 2020

@author: pierr
"""

a ="""[{'url': 'https://www.kijiji.ca/v-house-for-sale/red-deer/red-deer-house-for-sale/1515579814', 'price': '389', 'address': '55 Webster Dr, Red Deer, AB T4N 7G9, Canada', 'longitude': -113.8381218, 'latitude': 52.2519382, 'jurisdiction': 'alberta', 'visit': 0, 'full_
description': 'Excellent 5 bedroom family home in Westlake with oversized detached garage, 30 x 24. Close to college, several elementary and middle schools and Heritage Ranch. Public transportation enroute. Possession can be immediate. Listed for $389,900, large ma
ster bedroom, AC, underfloor heat in basement', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:17:30.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms
': '5', 'Bathrooms': '3'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/kamloops/investment-home-six-bedrooms/1515579833', 'price': '599999', 'address': '635 Gleneagles Dr, Kamloops, BC V2E 1Z6, Canada', 'longitude': -120.3545096, 'latitude': 50.6514363, '
jurisdiction': 'british-columbia', 'visit': None, 'full_description': 'Investment property producing over $5000 cash flow per month.This unique home is centrally located in Sahali close to TRU, schools, shopping and transit.Prime location for an investment property
 or easily can be used as a family home.There are two separate one bedroom suites that are self contained with separate laundry, kitchen and bathrooms.Upstairs has an open concept floor plan with kitchen, dining and living room. The area over the garage has been co
nverted into a bedroom with a large sliding glass door leading to a private deck.The current owner rents out each room with shared accommodation and maximizes his investment. A total of four bedrooms upstairs with the master bedroom having private access to the pri
vate backyard. This place is very well kept with updated landscaping, storage shed, garden, green house, underground sprinklers, and a detached shop that is used as a little guest cabin with insulated walls.Very private and accessible hiking out the back door.Other
 features include a large hot water tank, single car garage and lots of parking.All household goods are included in sale such as, beds, furniture, appliances, garden tools, ect.Includes four fridges, three stoves, two washer/dryers and dishwasher.24 hour notice req
uired for showings.$599,000Call, text or message back for more information, 604-417-2087.', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:17:38.000Z', 'residence_type': 'Hous
e', 'principal_characteristics': ({'Bedrooms': '6+', 'Bathrooms': '3', 'Size (sqft)': '2480'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/mississauga-peel-region/fully-renovated-3-b-r-2-kit-freehold-t-house-with-fin-bsm-at-pri/1515579824', 'price': '5899
99', 'address': '25 Jackman Dr, Brampton, ON L6S 2L8, Canada', 'longitude': -79.7240975, 'latitude': 43.7406379, 'jurisdiction': 'ontario', 'visit': 0, 'full_description': '25 Jackman DrBrampton Ontario L6S 2L7Newly Renovated & Highly Upgraded Freehold End Unit Tow
n House Features Living/Dining Combined Walks Out To Sunroom To Privately Fenced Backyard; New Updated Eat-In Kitchen With Breakfast Area; 3 Bright & Spacious Bedrooms,2 Upgraded Full Washrooms; Professionally Finished Basement With In Law Suite: Rec Room/Kitchen/3
 Pc Bath. Single Car Garage W/Extra Wide Driveway For 2 Car Parking; Large Deck At The Front; Potential For Separate Entrance.If You want to book the appointment to see this house, please feel free to contact me at 416-520-4931 or you can always visit my website to
 see more listingsRaman Gogna (P.Eng)Sales RepHomeLife Miracle Realty BrokerageCell: 416-520-4931http://www.homemajors.com', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:17:
34.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '3', 'Bathrooms': '2'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/nanaimo/university-district-home-with-shop/1515579221', 'price': '655000', 'address': '6-624 Shepherd Ave,
Nanaimo, BC V9R 3X4, Canada', 'longitude': -123.9507195, 'latitude': 49.1540277, 'jurisdiction': 'british-columbia', 'visit': None, 'full_description': 'Here is the opportunity you’ve been looking for. A house in the heart of university district on .38 of an acre w
ith a potential easy to add mortgage helper and a 30x34 wired shop with 13’ ceilings.This home is close to ALL levels of schooling, all are within walking distance.This home has 3 bedrooms upstairs and 1 bedroom down. However the downstairs can be easily converted
into a suite; as a separate entrance all ready exists from previously having been suited. Or leave it as is and have 4 bedrooms plus a second large living room family home. There is an office space as well as a large pantry and laundry room. The home is equipped wi
th new LED lighting throughout. The Kitchen is bright, and comes complete with new stainless steel appliances. It opens onto a large covered deck perfect for grilling in all seasons. You will find a Wood burning fireplace in the lower level with a brick chimney tha
t goes through the home for those cold winter nights. A well maintained lawn with a playground for the kids. The backyard has a separate fenced area for a pet or above ground pool. An outdoor fire pit completes the backyard with custom log bench seating. A must see
.More photos available. Send email address for more photos. Home is ready to show and quick possession is available.Willing to pay commission to relator who brings a buyer.*SCHEDULING SHOWINGS FOR AUGUST 2nd*', 'title': 'Propriétaires en difficulté financière, REPR
ISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:13:57.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '4', 'Bathrooms': '2', 'Size (sqft)': '2400'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sal
e/cambridge/coming-soon-to-mls-home-for-sale-minutes-west-of-kitchener/1515579821', 'price': '575000', 'address': '1887 Notre Dame Dr, St. Agatha, ON N0B 2L0, Canada', 'longitude': -80.63067989999999, 'latitude': 43.4368101, 'jurisdiction': 'ontario', 'visit': 0, '
full_description': "Welcome to St. Agatha located minutes from Kitchener/Waterloo. Don't miss out on the rare opportunity to secure your piece of rural living minutes from the city. This lovely 2-story 3 Bedroom 1.5 Bath home has been renovated top to bottom outsid
e upgrades include brand new concrete driveway (2020), premium vinyl siding(2017), New front & rear deck (2017), The private yard provide the perfect setting for those quiet summer nights. Walking inside, you will be impressed by the beautiful open concept main lev
el featuring high-grade laminate throughout leading you to the recently updated kitchen (2017) with Large Island, Quartz countertops, SS appliances, including a Gas stove. Inside upgrades include main lvl powder room(2017) Second lvl Bath(2018) Plumbing(2017) Insul
ation(2017) Electrical(2017) Basement(2018) Central air(2018) Furnace(2012) Shingles(2010). This home is a must-see; with all the work done, move in kick back and enjoy.Looking for additional information contact me today (photos coming soon)Trevor LandryDirect 519.
722.7207Office 519.570.4663Email trevor.landry@c21.ca", 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:17:32.000Z', 'residence_type': 'House', 'principal_characteristics': ({'
Bedrooms': '3', 'Bathrooms': '1.5', 'Size (sqft)': '1790'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/windsor-area-on/west-windsor-house-for-sale/1514452689', 'price': '340000', 'address': '321 Rankin Ave, Windsor, ON N9B 2R6, Canada', 'longitude': -83.
06283719999999, 'latitude': 42.3098458, 'jurisdiction': 'ontario', 'visit': 379, 'full_description': 'Beautiful home at 321 Rankin Ave Windsor. Five large bedrooms and two full baths. Covered porch, 1.5 large garage. Hardwood and lifetime luxury vinyl throughout ho
use. One bath features UTile. Stove, fridge, washer dryer and dishwasher included. Great for fist time buyers, large family or investors. Five minute walk to U of Windsor. Offered at $340,000', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION.
..', 'city': 'Laval / North Shore', 'date_posted': '2020-07-26T19:45:21.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '5', 'Bathrooms': '2'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/city-of-toronto/bathurst-st-vaughan-2b
dr-2bths/1515579035', 'price': '699000', 'address': 'Bathurst St, Thornhill, ON L4J, Canada', 'longitude': -79.4518046, 'latitude': 43.8177815, 'jurisdiction': 'ontario', 'visit': 0, 'full_description': 'Price: $699000 / $2207/mo*:*Fully Renovated 2 Bedroom 2 Bathr
oom* We Welcome You To The Luxury Living And Comfort At Thornhills *Promenade Towers*. Beautifully Renovated & Completely Upgraded. Open Concept Layout With Custom Dream Kitchen W/ Tons Of Cabinetry, Brand New Built-In S/S Appliances, Quartz Countertops, Custom Cei
ling Designs W/ Led Pot Lights, Smooth Ceilings, Paneling, Large Bedrooms, Renovated Bathrooms With Upgraded Vanities & Glass Shower. Crown Mouldings! Fireplace!Stainless Steel Counter Depth Fridge Freezer, S/S Built-In Dishwasher, Glass Top Stove, Sleek Hood, Fron
t Load Washer & Dryer, All Closet Organizers, All Window Coverings (Modern Zibra Blinds Throughout) And All Light Fixtures.For faster response, please use the contact form and provide a valid name and phone number and I will be in touch.For more information copy &
paste this link into your web browser: https://www.hmemkt.com/MB962LWe have access to literally thousands of properties!Visit our website at https://www.hmemkt.com/newlistings Try out our property search tools and get immediate results.All payments are based on 20%
 down payment at 2.99% down amortized over 30 on OAC.**Instant Approvals On Mortgage rates from as low as 2.79% APRListing Office: RE/MAX REALTRON REALTY INC., BROKERAGE', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval /
North Shore', 'date_posted': '2020-08-01T21:12:36.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '2', 'Bathrooms': '2'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/city-of-toronto/semi-detached-3-1-bedroom-house/1515579968',
 'price': '0', 'address': ', Brampton L7A1S2 ON, Canada', 'longitude': -79.8140907, 'latitude': 43.6897994, 'jurisdiction': 'ontario', 'visit': 0, 'full_description': "Absolutely Stunning 3+1 Bedrooms' & 4 Washrooms' Semi-Detached Home In A Great Location No Side W
alk W/Lots Of Upgrades; Living Room Combined W/Dining; Eat In Kitchen W/Granite Counter Top, Master Br With 4Pc Ensuite/Walk In Closet; All Washrooms W/Granite Counter Tops, Beautiful Fenced Backyard; Finished Basement W/Rec/Bedroom/Bathroom; Large Driveway W/Poure
d Concrete In Backyard/Sides W/4 Parking.......Lots Of Potential", 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:18:20.000Z', 'residence_type': 'House', 'principal_characteri
stics': ({'Bedrooms': '3', 'Bathrooms': '4', 'Size (sqft)': '1800'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/city-of-toronto/brent-rd-east-gwillimbury-4bdr-4bths/1515579375', 'price': '1385000', 'address': 'Brent Rd, East Gwillimbury, ON L9N, Canada',
 'longitude': -79.48707569999999, 'latitude': 44.108655, 'jurisdiction': 'ontario', 'visit': 0, 'full_description': 'Price: $1385000 / $4372/mo*Welcome To This Beautiful Home Located In Holland Landing! This Home Features Granite Countertops In Kitchen & Master Bat
h, Smooth Ceilings, Hardwood Floors Throughout, Stone Patio In Rear, Built-In Appliances, Sprinkler System In Front & Rear, & Built-In Security System. In Close Proximity To Schools, Parks, Shopping, & All Other Amenities!For faster response, please use the contact
 form and provide a valid name and phone number and I will be in touch.For more information copy & paste this link into your web browser: https://www.hmemkt.com/QC226QWe have access to literally thousands of properties!Visit our website at https://www.hmemkt.com/ne
wlistings Try out our property search tools and get immediate results.All payments are based on 20% down payment at 2.99% down amortized over 30 on OAC.**Instant Approvals On Mortgage rates from as low as 2.79% APRListing Office: PURPLEBRICKS, BROKERAGE', 'title':
'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:14:55.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '4', 'Bathrooms': '4'}, {})}, {'url': 'https://www.kij
iji.ca/v-house-for-sale/vernon/breathtaking-views-of-okanagan-lake-close-by-beach-peaceful/1515580062', 'price': '0', 'address': '2095 Boucherie Rd, Westbank, BC V4T 1Z5, Canada', 'longitude': -119.6084221, 'latitude': 49.8251561, 'jurisdiction': 'british-columbia'
, 'visit': 0, 'full_description': 'Well maintained, private with large patio , covered deck. Cozy 3 bedroom, 2 sheds, larger open kitchen concept. Comfortable living with reasonable living expenses. Peaceful, chilly nights with a awesome newer wood stove. Great ven
tilation and new A/C. This is a fantastic place to live. No rentals and registered/certified dogs only. Ready to move - in. Sunny from all the windows. Low pad rent of 485 per month and 100$ taxes per year over 65. Great neighbors and park, marina, shopping close b
y. Drop by and take a look-see.', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:18:57.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '3', 'Bathr
ooms': '1', 'Size (sqft)': '865'}, {})}, {'url': 'https://www.kijiji.ca/v-maison-a-vendre/laurentides/maison-a-prevost-cle-en-main/1515579856', 'price': '349900', 'address': 'J0R 1T0, Canada', 'longitude': -74.050975, 'latitude': 45.8671566, 'jurisdiction': 'quebec
', 'visit': 0, 'full_description': '3 + 1 chambres, 3 salles de bain, salle de lavage, systme alarme,sous-sol fini, foyer combustion lente ,plancher bois franc, air climatis murale neuve 18000 btu, toiture et grand balcon refait 3 ans, trs grand garage, Piscine hor
s -terre, spa 6 places, cabanon, cours priv cltur, gazebo 10x12, entre 4 places pav uni et rue cul de sac tranquilleSitu  1 minutes 117 et 5 minde la 15En entrant  PrvostPour plus informations ou photosVous pouvez communiquer su 514-298-8164 ou 450-368-0460', 'titl
e': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:17:46.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '4', 'Bathrooms': '2.5'}, {})}, {'url': 'https://w
ww.kijiji.ca/v-house-for-sale/city-of-toronto/frontenac-ave-toronto-6bdr-5bths/1515579836', 'price': '2980000', 'address': 'Frontenac Ave, Toronto, ON M5N, Canada', 'longitude': -79.42420969999999, 'latitude': 43.7178757, 'jurisdiction': 'ontario', 'visit': 0, 'ful
l_description': "Price: $2980000 / $9407/mo*Awe-Inspiring Modern Masterpiece By Treasure Hill. Att. To Detail At Every Turn. Unrivalled Quality & Design. Near 4700 Sq.Ft. Of Living Spc,Mrble Accents, Quarter Cut Oak Flrs, Htd Lwr Lvl. Custom Kit. W/ 15' Marble Isla
nd & Wolf Appls. Lwr Lvl Boasts W/O, Hm Theater, Nanny's Quarters & 2nd Kitchen Connection Ready. Steps To Ttc, Metro. Canadian Tire, And Close To Havergal, Tfs, Cresent, Ucc, Bss. Enjoy Boutiqu Shops And Eatery At Yordale Mall Minutes DriveSubzero Fridge, Wolf Gas
 Stove & Hood, Dishwasher, Washer, Dryer, Light Fixtures, Window Coverings, Instant Hwt, Central Vaccum Sys, New Stonework Back Yard And Sidewalk @$14,000, New Shed In Back Yard @$1000For faster response, please use the contact form and provide a valid name and pho
ne number and I will be in touch.For more information copy & paste this link into your web browser: https://www.hmemkt.com/IQ276DWe have access to literally thousands of properties!Visit our website at https://www.hmemkt.com/newlistings Try out our property search
tools and get immediate results.All payments are based on 20% down payment at 2.99% down amortized over 30 on OAC.**Instant Approvals On Mortgage rates from as low as 2.79% APRListing Office: BAY STREET GROUP INC., BROKERAGE", 'title': 'Propriétaires en difficulté
financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:17:39.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '6+', 'Bathrooms': '5'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/city
-of-toronto/briar-hill-ave-toronto-3bdr-2bths/1515580246', 'price': '734500', 'address': 'Briar Hill Ave, York, ON M6B 1M7, Canada', 'longitude': -79.4505368, 'latitude': 43.7028531, 'jurisdiction': 'ontario', 'visit': 0, 'full_description': "Price: $734500 / $2319
/mo*This Immaculate, Professionally-Designed 2-Story Condo With A Private Roof Top Terrace Exudes Modern Elegance. The Generous Living Space & Stylish Finishes Is The Perfect Setting For Relaxing & Entertaining While Enjoying Views Of The Cn Tower. Special Highligh
ts Incl Charming Kitchen, Designer Feature Stone Wall, Bbq Gas Line, & Over 17K In Upgrades. All The Urban Amenities You Could Need For The Best Value In The City!Walking Distance To Beltline Trail, Easy Access To 401, Minutes To Shopping, Restaurants, Eglinton Cro
sstown Ttc Subway. All Elf's, S/S Fridge,Built-In Microwave,Dishwasher,Stove,Stacked Washer & Dryer,Custom Window Coverings, 1 Lrg LockerFor faster response, please use the contact form and provide a valid name and phone number and I will be in touch.For more infor
mation copy & paste this link into your web browser: https://www.hmemkt.com/TA387FWe have access to literally thousands of properties!Visit our website at https://www.hmemkt.com/newlistings Try out our property search tools and get immediate results.All payments ar
e based on 20% down payment at 2.99% down amortized over 30 on OAC.**Instant Approvals On Mortgage rates from as low as 2.79% APRListing Office: RIGHT AT HOME REALTY INC., BROKERAGE", 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city
': 'Laval / North Shore', 'date_posted': '2020-08-01T21:20:09.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '3', 'Bathrooms': '2'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/city-of-toronto/briarwood-cres-kingsville-5bdr-4
bths/1515580624', 'price': '999000', 'address': 'Briarwood Crescent, Kingsville, ON N0R, Canada', 'longitude': -82.6977228, 'latitude': 42.0339383, 'jurisdiction': 'ontario', 'visit': 0, 'full_description': 'Price: $999000 / $3154/mo*Amazing 2 Storey Home On Quiet
Street In Desirable Kingsville With 187.37 Ft Of Lakefront. Airy, Open Concept. Living Room W/ Double Fireplace, Large Sunroom, 2 Main Flr Bedrooms, 1 With French Doors Outside. 2nd Storey Has 3 Additional Bedrooms With Gorgeous Lake Views, 2 Walk In Closets In The
 Master, Plus En-Suite And Bonus Room Off The Master For Office, Nursery Or Beauty Room. Partially Finished Basement. Lots Of Custom Built Ins Throughout.For faster response, please use the contact form and provide a valid name and phone number and I will be in tou
ch.For more information copy & paste this link into your web browser: https://www.hmemkt.com/UF464VWe have access to literally thousands of properties!Visit our website at https://www.hmemkt.com/newlistings Try out our property search tools and get immediate result
s.All payments are based on 20% down payment at 2.99% down amortized over 30 on OAC.**Instant Approvals On Mortgage rates from as low as 2.79% APRListing Office: PURPLEBRICKS, BROKERAGE', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', '
city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:22:26.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '5', 'Bathrooms': '4'}, {})}, {'url': 'https://www.kijiji.ca/v-maison-a-vendre/laval-rive-nord/proprietaires-en-difficulte
-financiere-reprises-succession/1515577146', 'price': '0', 'address': 'Chemin de Lachalade, Lorraine, QC J6Z 4E8, Canada', 'longitude': -73.7910466, 'latitude': 45.6772483, 'jurisdiction': 'quebec', 'visit': 0, 'full_description': 'Profitez de mes contacts et de mo
n exprience 33 ANS en immobilier, ( voir mon profil su Linkedin) pour la recherche de votre prochaine proprit  Montral et sur la RIVE-NORD de Montral. Je vous trouverez la perle rare grce  mes outils de reprage trs efficace!Soyez au 1 er RANG pour recevoir GRATUITE
MENT et rapidement les nouvelles inscriptions qui correspondent  vos critres et les nouvelles REPRISES DE FINANCE, maison qui faut vendre rapidement...SUCCESSION!Les bonnes opportunits ne restent pas longtemps sur le march. Profitez de mon service informatique auto
matis  la fine pointe de la technologie pour trouver la bonne maison. Appelez-maintenant pour vous inscrire gratuitement au 450-965-6921Services GRATUITS et SANS OBLIGATION de votre part!OBTENEZ toutes les nouvelles inscriptions de toutes les agences immobilires co
rrespondant  vos critres de recherche ds qu’elles apparaissent sur le march, GRATUITEMENT et SANS OBLIGATION, par notre service VIP pour acheteurs www.ListeDeRepriseGratuite.comVendeurs en difficults, REPRISE de FINANCE, succession, maisons en pr-reprise… Il faut v
endre absolument et rapidement! Ce SERVICE est GRATUIT et SANS OBLIGATION de votre part! Pour recevoir la liste www.ListeDeRepriseGratuite.comATTENTION propritaire! Vous aimeriez savoir combien vaut votre maison? Ce SERVICE est GRATUIT et SANS OBLIGATION de votre p
art! courriel: louis.renaud@videotron.caGracieuset de : Louis Renaud BAA, FRICourtier Immobilier agr et certifi QSC (Qualit Service Clientle)', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted':
 '2020-08-01T21:01:10.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '3', 'Bathrooms': '2'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/calgary/legal-4-plex-in-mayland-heights-for-sale/1515580032', 'price': '0', 'address': '
, Calgary T2E 6A7 AB, Canada', 'longitude': -114.0054155, 'latitude': 51.06352829999999, 'jurisdiction': 'alberta', 'visit': None, 'full_description': 'Attractive Legal 4 Plex FOR SALE. 2-3 BEDROOM AND 2-2 BEDROOM UNITS Newer 4 furnaces and 4 hot water tanks. Torch
on roof in 2012. Two laundry/utility rooms Tenants pay own utilities. Excellent location close to DT, Deerfoot and great access to shopping, transit and schools. Off street parking in rear. Low maintenance exterior. Owner retiring. Excellent time to buy with rates
so low.', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:18:46.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '6+', 'Bathrooms': '4'}, {})}, {'ur
l': 'https://www.kijiji.ca/v-house-for-sale/mississauga-peel-region/brampton:-detached-home-with-finished-basement-and-sep-entrance/1515580297', 'price': '799000', 'address': 'Brampton, ON, Canada, L6P5T6', 'longitude': -79.76242, 'latitude': 43.73155, 'jurisdictio
n': 'ontario', 'visit': 0, 'full_description': "BRAMPTON: Detached home with finished basement and separate entrance for only $799,000 in north-west of Brampton. Available till Aug-02.Shows 10 ++. Fully Upgraded 4 Bedroom Detached Home On A Premium Pie Shape Lot,!!
 Spacious And Functional Layout ,Separate Family & Living Room's. Newer Upgraded Kitchen W/Quartz Counter Top & New High-End S/S Appliances*Newer Roof*Newer A/C* Newer Central Vacuum & Attachments. All 4 Br's Are Good Size & Upgraded Washrooms.Professionaly Finishe
d Basement W/ Large Bedroom, Living Room & Full Washroom. Beautiful Stone Patio In The Backyard And Lot More !!Call Gurinder @ 647-821-8400 for more information", 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Sho
re', 'date_posted': '2020-08-01T21:20:26.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '4', 'Bathrooms': '3'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/mississauga-peel-region/house-for-sale/1515577834', 'price': '745000'
, 'address': 'CALEDON, Canada', 'longitude': -79.87448359999999, 'latitude': 43.8363372, 'jurisdiction': 'ontario', 'visit': 0, 'full_description': '( PRIVATE SALE ONLY )Back to back semi detached no back yard, 3 story house 2028 square feet , no sidewalk with 3 ca
r parking nice terrace in front on 2nd floor for sale on assignment in caledon under construction closing in Nov / 2020( PRICE $745,000 included assignment fee )Call for info :- 4167103306', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...'
, 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:05:14.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '3', 'Bathrooms': '3', 'Size (sqft)': '2028'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/victoria-bc/broadm
ead-rancher/1515577625', 'price': '0', 'address': '4479 Shadywood Pl, Victoria, BC V8X 4C5, Canada', 'longitude': -123.3693618, 'latitude': 48.4953565, 'jurisdiction': 'british-columbia', 'visit': 0, 'full_description': 'Beautiful rancher tucked in a quiet culdesac
 which, though well treed, offers lots of sunshine in the house and private yard. Many updates throughout! Main floor has over 2600 ft sq, offering 4 bedrooms, 3 full bathrooms, living room, family room, dining room, kitchen, and mud room/laundry. This last room op
ens to the oversized double garage. Kitchen has lots of cupboards, granite counters, double stainless farmers sink, prep sink, huge island, side by side full fridge/full freezer, instant hot dispenser, huge pantry, eating nook, and sliding doors to the patio. En-su
ite and main bathroom have heated tile flooring, with oak hardwood flooring most everywhere else. The lower level has about 600sq ft of living space, including a wet bar, separate laundry, 4pc bathroom, and an open area which lends itself to being a rec room/media
room/studio/office....... The rest of the lower level is a crawl space, with good areas for extra storage.', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:04:05.000Z', 'resid
ence_type': 'House', 'principal_characteristics': ({'Bedrooms': '4', 'Bathrooms': '4', 'Size (sqft)': '3200'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/city-of-toronto/nobu-assignment-sale-35-mercer-st-:-3-bed-den-2-bath/1515577764', 'price': '1850000'
, 'address': '35 Mercer St, Toronto, ON M5V 1H2, Canada', 'longitude': -79.39108130000001, 'latitude': 43.6454371, 'jurisdiction': 'ontario', 'visit': 0, 'full_description': '*Asking $1,850,000*East tower*40th floor, south west view*Parking and locker included', 't
itle': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:04:53.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '3', 'Bathrooms': '2', 'Size (sqft)': '1049'},
{})}, {'url': 'https://www.kijiji.ca/v-maison-a-vendre/laval-rive-nord/bungalow-avec-bachelor-et-gros-garage-en-campagne/1515578000', 'price': '289900', 'address': '21 Rue Cliche, Saint-Lin - Laurentides, QC J5M 2B7, Canada', 'longitude': -73.8002807, 'latitude': 4
5.8311106, 'jurisdiction': 'quebec', 'visit': 0, 'full_description': 'Ideal premier achat, bachelor conforme avec 2 sorties exterieures et 2 entrees electrique independante. Cuisine avec beaucoup de rangement. Il y a une piece au sous-sol pour le proprietaire. Gran
d terrain a la campagne situe a mi-chemin entre St-Jerome et La Plaine. NB: REVENU s-sol etait loue $615/ mois non chauffe. OCCUPATION RAPIDE possible.NB: 2 adresses, 2 entrees electriques independantes, 2 entrees exterieures au sous-sol, 2 reservoirs a eau chaude
CONFORME a la reglementation.Autres services GRATUITS et SANS OBLIGATION de votre part!OBTENEZ toutes les nouvelles inscriptions de toutes les agences immobilieres correspondant a vos criteres de recherche des qu’elles apparaissent sur le marche GRATUITEMENT et SAN
S OBLIGATION, par notre service VIP pour acheteur : allez visiter www.louisrenaud.comVendeurs en difficulte: REPRISE de FINANCE, succession, maisons en reprise… faut vendre absolument et rapidement. Pour recevoir la liste allez au : : listedereprisegratuite.comATTE
NTION proprietaire! Vous aimeriez savoir combien vaut votre maison? Visitez : www.louisrenaud.comGracieusete de :Louis Renaud BAA, FRICourtier Immobilier agree et certifie QSC (Qualite Service Client )Contact Immobilier LR , Agence Immobiliere 450-965-6921', 'title
': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:06:14.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '3', 'Bathrooms': '2'}, {})}, {'url': 'https://www.
kijiji.ca/v-house-for-sale/city-of-toronto/elm-grove-ave-toronto-6bdr-5bths/1515577808', 'price': '2200000', 'address': 'Elm Grove Ave, Toronto, ON M6K, Canada', 'longitude': -79.43093189999999, 'latitude': 43.6399777, 'jurisdiction': 'ontario', 'visit': 0, 'full_d
escription': "Price: $2200000 / $6945/mo*Detached Legal Duplex / Multi-Unit W/ Great Net Inc. In Lively Parkdale Steps From Queen St W Vibrant Commercial Strip. Detached 2.5 Story On Milky Way Lane, Opp For More $$$ By Building Above The Existing Attached Garage. L
arge Main Fl. Unit With Mixed-Use Potential. Existing Aaa Tenants. Diverse Units With Own Charms & Character. Walk Thru W/Virtual Tour.Reno'd 2012: Lam Flooring, 5 Modern Baths, Dbl Pane Windows, Int/Ext Doors W/Keyless Entry, Pot Lights, Plaster Crown Molding, 2 O
utdoor Seating Areas, Rm Control Garage Door. Easy Access To Hwy & Dt Core. Contact La For Financials & Insp.For faster response, please use the contact form and provide a valid name and phone number and I will be in touch.For more information copy & paste this lin
k into your web browser: https://www.hmemkt.com/OT944KWe have access to literally thousands of properties!Visit our website at https://www.hmemkt.com/newlistings Try out our property search tools and get immediate results.All payments are based on 20% down payment
at 2.99% down amortized over 30 on OAC.**Instant Approvals On Mortgage rates from as low as 2.79% APRListing Office: PSR, BROKERAGE", 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-
01T21:05:06.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '6+', 'Bathrooms': '5'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/city-of-toronto/highgate-pl-mississauga-5bdr-4bths/1515577393', 'price': '1329999', 'address': 'H
ighgate Pl, Mississauga, ON L4W, Canada', 'longitude': -79.6173051, 'latitude': 43.6253552, 'jurisdiction': 'ontario', 'visit': 0, 'full_description': 'Price: $1329999 / $4199/mo*Elegant 2-Storey Family Home Located On A Quiet Street In Golden Orchard Estates. Over
 2400 Sqft. Contemporary Layout Offering Generous Sized 4+1 Bed, Recently Renovated Sun-Filled Modern Kitchen W/ S/S Appliances, Quartz Counters , W/O To Private Deck Leading To Lush Green Backyard And Updated Hardwood Flooring Throughout. Basement Offers Grand Ope
n Rec Room For Entertaining W/ New Flooring, +1 Bed And 4-Pce Bath.Easy Access To Major Hwys, Public Transportation Stores And Grocery. All Existing Appliances Incld. Flooring & Washroom Updates (2017). Kitchen, Driveway, & Roof (2019). Exclusions: Din Rm & Master
Chandelier, Din Rm Drapes, Pool Table, BarFor faster response, please use the contact form and provide a valid name and phone number and I will be in touch.For more information copy & paste this link into your web browser: https://www.hmemkt.com/JS927CWe have acces
s to literally thousands of properties!Visit our website at https://www.hmemkt.com/newlistings Try out our property search tools and get immediate results.All payments are based on 20% down payment at 2.99% down amortized over 30 on OAC.**Instant Approvals On Mortg
age rates from as low as 2.79% APRListing Office: ROYAL LEPAGE REAL ESTATE SERVICES LORETTA PHINNEY, BROKERAGE', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:02:44.000Z', 'r
esidence_type': 'House', 'principal_characteristics': ({'Bedrooms': '5', 'Bathrooms': '4'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/edmonton/2003-manufactured-home-for-sale-in-hinton-ab/1515578226', 'price': '234000', 'address': '159 Skogg Ave, Hinton
, AB T7V 1A5, Canada', 'longitude': -117.5288909, 'latitude': 53.42634899999999, 'jurisdiction': 'alberta', 'visit': 0, 'full_description': "Call Melissa Hicks, 780-223-2225 REALTOR Coldwell Banker Hinton Real Estate to book your viewing today! Welcome to 159 skogg
 Ave, located in the East Hardisty area of Hinton. This 3 bedroom, 2 bath home was manufactured in 2003, has been meticulously cared for & feels brand new inside & out. The home is 1216 sq.ft & is situated on a developed, OWNED lot! The kitchen has new counter tops
, large pantry & newer black appliances. Fantastic open concept home from the kitchen to the living room with cathedral ceilings & newly installed grey tone vinyl plank flooring. This home has 3 bedrooms, the master is spacious with a gorgeous en-suite featuring a
large soaker tub & separate shower. Walk-out to the deck for easy entertaining & BBQ`s. Outside offers 3 storage sheds & developed gardens with perennials. Double parking or room for an RV. All appliances included, great opportunity to own your own home for less th
an most rent's in Hinton.", 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:07:45.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '3', 'Bathrooms':
 '2', 'Size (sqft)': '1216'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/city-of-toronto/erskine-ave-toronto-2bdr-3bths/1515578196', 'price': '1050000', 'address': 'Erskine Ave, Toronto, ON M4P 1Y5, Canada', 'longitude': -79.3964577, 'latitude': 43.71168
28, 'jurisdiction': 'ontario', 'visit': 0, 'full_description': "Price: $1050000 / $3315/mo*Tridel Luxury Built. Elegant South East Corner Unit In The Heart Of Yonge/Eglinton. Sun-Filled Unit With Stunning Panoramic View Through Wrap Around Windows. Spacious Kitchen
 With Island. Plenty Of Storage, Under-Mount Lighting Above Quartz Countertop & Slab Backsplash. European Built Appliances. Walk To Shops, Cafe, Restaurants & Subway. High Ranking Schools, Guest Suites, Amazing 5 Star Amenities. Highly Functional 992Sqft Layout.Who
le Unit Smooth 9' Ceiling. Ceiling Light In Living Rm, Panelled Fridge & D/W, Cooktop, S/S Oven & Microwave. Lg Large W/D With Hand Wash & Steam Option. All Elf, Window Covering.For faster response, please use the contact form and provide a valid name and phone num
ber and I will be in touch.For more information copy & paste this link into your web browser: https://www.hmemkt.com/RB266IWe have access to literally thousands of properties!Visit our website at https://www.hmemkt.com/newlistings Try out our property search tools
and get immediate results.All payments are based on 20% down payment at 2.99% down amortized over 30 on OAC.**Instant Approvals On Mortgage rates from as low as 2.79% APRListing Office: HOMELIFE/GTA REALTY INC., BROKERAGE", 'title': 'Propriétaires en difficulté fin
ancière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:07:29.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '2', 'Bathrooms': '3'}, {})}, {'url': 'https://www.kijiji.ca/v-maison-a-vendre/laurent
ides/chalet-bord-de-l-eau-lac-chapleau-la-minerve/1515578472', 'price': '389000', 'address': 'La Minerve, Canada', 'longitude': -74.9848597, 'latitude': 46.18176889999999, 'jurisdiction': 'quebec', 'visit': 0, 'full_description': 'Situ  La Minerve au tres grand Lac
 Chapleau, Lac navigable. 150 pieds de plage de sable fin. Tout meubl et quip. Prt  emmnager. 5 chambres, 2 salles de bains, foyer au bois au rez-de-chausse, pole  bois au sous-sol.Terrain de 32000 pieds carrsTerrain en pente vers le lacQuai pour bateau et aussi qu
ai flottant pour s’amuser inclus. Aussi 2 kayak adulte 2 kayak enfants et 1 paddleboard inclusPlaisir t comme hiverSentier VTT et Motoneige30 minutes de TremblantVisite accepte avec pr-approbation bancaire seulement', 'title': 'Propriétaires en difficulté financièr
e, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:09:10.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '5', 'Bathrooms': '2', 'Size (sqft)': '2000'}, {})}, {'url': 'https://www.kijiji.ca/v-house-
for-sale/city-of-toronto/keele-st-dr-toronto-2bdr-2bths/1515581065', 'price': '529990', 'address': 'Keele St, North York, ON M3K 2C5, Canada', 'longitude': -79.485877, 'latitude': 43.7428762, 'jurisdiction': 'ontario', 'visit': 0, 'full_description': "Price: $52999
0 / $1673/mo*Mattamy's Saturday! First Floor Unit With Walk Up Entrance! Amazing 1B+D (Den Has Door) With 2 Bathrooms! Terrace, Modern Kitchen W/S.S. Appliances, & Quartz Counters. This Is A Lifestyle!! Enjoy Amenities Including Fitness Rm W/ Yoga Studio, Party Rm
(Indoor/Outdoor), Bbq, Area, & 24 Hour Concierge.Walk Out The Door To Enjoy The Massive Downsview Park, Subway Station & Local Amenities Are Steps Away. Includes: Fridge, Stove, D/W, Stackable W/D, 1 Locker + 1 Underground ParkinFor faster response, please use the
contact form and provide a valid name and phone number and I will be in touch.For more information copy & paste this link into your web browser: https://www.hmemkt.com/MD153YWe have access to literally thousands of properties!Visit our website at https://www.hmemkt
.com/newlistings Try out our property search tools and get immediate results.All payments are based on 20% down payment at 2.99% down amortized over 30 on OAC.**Instant Approvals On Mortgage rates from as low as 2.79% APRListing Office: REALTY EXECUTIVES INVESTMENT
 GROUP LTD., BROKERAGE", 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:24:56.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '2', 'Bathrooms': '2
'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/city-of-toronto/3-1-bedrooms-freehold-townhouse-in-demanded-area/1515578888', 'price': '0', 'address': ', Brampton L6Y5S9 ON, Canada', 'longitude': -79.7354307, 'latitude': 43.65882939999999, 'jurisdiction':
 'ontario', 'visit': 0, 'full_description': 'Very Specious, Bright And Well Maintained 3+1 Bedrooms Freehold Townhouse In Highly Demanded Area At The Back Of Sheridan College In Brampton. Corner Townhouse With Walkout Separate Entrance Bsmt. Upgraded Kitchen With Q
uartz Counter Top And Backsplash, Carpet Free House That Has Great View Of Pond And Green Trail For Walk And Run. Very Large Garage With Car Parking And Lot Of Spaces For Extra Storage. Perfect For First Time Buyer Of Investor. **', 'title': 'Propriétaires en diffi
culté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:11:42.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '3', 'Bathrooms': '4', 'Size (sqft)': '1700'}, {})}, {'url': 'https://www.kij
iji.ca/v-maison-a-vendre/laurentides/belle-maison-unifamiliale-demi-detache-possibilite-revenus/1515578478', 'price': '295000', 'address': 'Rue Charles, Mirabel, QC J7J 1H8, Canada', 'longitude': -73.9144622, 'latitude': 45.7088804, 'jurisdiction': 'quebec', 'visit
': 0, 'full_description': 'Tres belle propriete cle en main Avec possibilite de revenusPlein pieds avec demi sous sol fini avec 3 chambres beaucoup de rangement Salle de sejour et salle de bain avec doucheRez chausse plein pieds avec 2 chambres et. laveuse secheuse
 Plancher parquetterie et ceramique Thermopompe climatiseurs et chauffage tres economiqueDemi sous sol fini Plancher bois flottant 3 chambres , rangement , Salle de sejour et salle de pain avec douche Balayeuse centrale echangeur d air Venmar Grand garde robe de ch
ambreInclus rideaux et electros Et plus..Toiture faite 2007 Fenetres changes 2018Tres bien entretenu beaucoup de rangements pres de toutes les services de la gare rue Victor en fonction automne 2020Cloture toute arriere paysager avec 2 cabanons (1 cabanon fontaine)
 Grand Stationnement asphalte faite 4 places et plus possiblePres ecole et garderiePiste cyclable juste a 50 pieds et ski de fond ou marche l hiver et gare a 5 minutes de marche Pres des autoroutes 15 50 640 IGA SAQ JEAN COUTU UNIPRIX CAISSE POP BN.. et plus295000
taxes Incluses negociableA qui la chance par proprietaire 450 951 5647 Enquete de credit AGENT S ABSTENIR MERCI', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:09:12.000Z', '
residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '5', 'Bathrooms': '2', 'Size (sqft)': '2659'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/city-of-toronto/bathurst-st-vaughan-2bdr-2bths/1515578584', 'price': '699000', 'address': 'Bath
urst St, Thornhill, ON L4J, Canada', 'longitude': -79.4518046, 'latitude': 43.8177815, 'jurisdiction': 'ontario', 'visit': 0, 'full_description': 'Price: $699000 / $2207/mo*:*Fully Renovated 2 Bedroom 2 Bathroom* We Welcome You To The Luxury Living And Comfort At T
hornhills *Promenade Towers*. Beautifully Renovated & Completely Upgraded. Open Concept Layout With Custom Dream Kitchen W/ Tons Of Cabinetry, Brand New Built-In S/S Appliances, Quartz Countertops, Custom Ceiling Designs W/ Led Pot Lights, Smooth Ceilings, Paneling
, Large Bedrooms, Renovated Bathrooms With Upgraded Vanities & Glass Shower. Crown Mouldings! Fireplace!Stainless Steel Counter Depth Fridge Freezer, S/S Built-In Dishwasher, Glass Top Stove, Sleek Hood, Front Load Washer & Dryer, All Closet Organizers, All Window
Coverings (Modern Zibra Blinds Throughout) And All Light Fixtures.For faster response, please use the contact form and provide a valid name and phone number and I will be in touch.For more information copy & paste this link into your web browser: https://www.hmemkt
.com/OU813CWe have access to literally thousands of properties!Visit our website at https://www.hmemkt.com/newlistings Try out our property search tools and get immediate results.All payments are based on 20% down payment at 2.99% down amortized over 30 on OAC.**In
stant Approvals On Mortgage rates from as low as 2.79% APRListing Office: RE/MAX REALTRON REALTY INC., BROKERAGE', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:09:54.000Z',
'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '2', 'Bathrooms': '2'}, {})}, {'url': 'https://www.kijiji.ca/v-maison-a-vendre/longueuil-rive-sud/avis-de-60-jours-reprise-bancaire-j-achete-votre-maison/1515581231', 'price': '0', 'address': 'J3
X1G7, Canada', 'longitude': -73.4273867, 'latitude': 45.6756259, 'jurisdiction': 'quebec', 'visit': 0, 'full_description': 'J’achte votre maisonJe vous libre de votre fardeau financierSuccessionCommuniquez avec moi', 'title': 'Propriétaires en difficulté financière
, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:25:56.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '2', 'Bathrooms': '1'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/city-of-toronto
/want:-cash-buyer-looking-for-house-at-agincourt-steeles-miliken/1515580855', 'price': '900000', 'address': ', City of Toronto M5S2A2 ON, Canada', 'longitude': -79.38694269999999, 'latitude': 43.66465729999999, 'jurisdiction': 'ontario', 'visit': 0, 'full_descripti
on': "WANTED: We have CASH BUYER LOOKING FOR TOWNHOUSE, SEMI AND DETACH HOUSE AT THE FOLLOWING AREA:SCARBOROUGH:AGINCOURT / STEELES / MILIKEN / L'AMOREAUXMARKHAM:MILLIKEN MILL EAST / MILLIKEN MILL WEST / MIDDLEFIELD /CEDARWOODPRICE UNDER 1.2 MILLIONIf you or your f
riend have house at these area want to sell, Please call me ASAPwe have solid buyers!We have a strong internal sales network and effective negotiation skills. We have helped our clients to BUY AND SELL MANY house this year. Collaborate with us, Buy or sell your pro
perty and make your dream. WE HAVE BUYERS!Please contact Mike 647 872 1262\x05 Email me at:toronto9933@gmail.com", 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:23:53.000Z',
'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '3', 'Bathrooms': '3', 'Size (sqft)': '111'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/city-of-toronto/starwood-dr-mississauga-3bdr-3bths/1515582634', 'price': '825000', 'address': '
Starwood Dr, Mississauga, ON L5R, Canada', 'longitude': -79.6782364, 'latitude': 43.5991875, 'jurisdiction': 'ontario', 'visit': 0, 'full_description': 'Price: $825000 / $2604/mo*Outstanding Greenpark-Built Freehold T/Home In Desirable Central Mississauga Area. Upd
ated & Renovated Home With Hardwood Flrs & Laminate Throughout. Oak Stairs, Large Kitchen With Quartz Counters,Quartz Backsplash, W/O To Sunny Private Gdns. 1791 Sqft(Mpac), Large Rooms, Finished Basement, New Roof 2018. Indoor Entry To Garage,Open Concept Layout!5
 Appliances, All Window Covs, All Light Fixtures. Garage Door Opener & Remote, Central Air, 2 Yr Old Gas Furnace Rented For $66.46/Month Plus Tax (To Be Assumed). R/I Washroom In Basement. Large Cantina. Pot Lights Thruout Main&Lower Lvls.For faster response, pleas
e use the contact form and provide a valid name and phone number and I will be in touch.For more information copy & paste this link into your web browser: https://www.hmemkt.com/JJ816RWe have access to literally thousands of properties!Visit our website at https://
www.hmemkt.com/newlistings Try out our property search tools and get immediate results.All payments are based on 20% down payment at 2.99% down amortized over 30 on OAC.**Instant Approvals On Mortgage rates from as low as 2.79% APRListing Office: RE/MAX REALTY ENTE
RPRISES INC., BROKERAGE', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:32:25.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '3', 'Bathrooms': '
3'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/city-of-toronto/aberdeen-blvd-midland-5bdr-4bths/1515581616', 'price': '1450000', 'address': 'Aberdeen Blvd, Midland, ON, Canada', 'longitude': -79.8630148, 'latitude': 44.7499792, 'jurisdiction': 'ontario'
, 'visit': 0, 'full_description': 'Price: $1450000 / $4577/mo*Luxurious Waterfront W/ In-Law Capability In Midland.Nothing Has Been Overlook From The Marble Floor To The Tile Metal Roof.Incredible Home Features Open Concept Main Flr W/ Views Of Georgian Bay,Ample N
atural Light,Immaculate Kitchen W/ High-End Appliances,Slate Countertops,Master Bed W/ Stunning Sunrises,Spa-Like Ensuite.Finished Lowel Level W/ 2nd Kitchen,Radiant Heat Throughout.Enjoy The Deck W/ Unobstructed WaterViews,Private Dock & More.Close To All Amenitie
s,Restaurants,Shopping.Note:Sq.Ft. Measures On Realtor.Ca Are Exterior*24Hrs Irrevocable On All Offers*For faster response, please use the contact form and provide a valid name and phone number and I will be in touch.For more information copy & paste this link into
 your web browser: https://www.hmemkt.com/RJ996YWe have access to literally thousands of properties!Visit our website at https://www.hmemkt.com/newlistings Try out our property search tools and get immediate results.All payments are based on 20% down payment at 2.9
9% down amortized over 30 on OAC.**Instant Approvals On Mortgage rates from as low as 2.79% APRListing Office: KELLER WILLIAMS EXPERIENCE REALTY, BROKERAGE', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore',
'date_posted': '2020-08-01T21:27:37.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '5', 'Bathrooms': '4'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/nelson/custom-home-and-shop-on-4-mountainview-acres/1511288572', 'price':
'669000', 'address': '8946 Austyn Rd, Slocan, BC V0G 2C0, Canada', 'longitude': -117.4550102, 'latitude': 49.7571265, 'jurisdiction': 'british-columbia', 'visit': 849, 'full_description': "Custom timber accented home on gorgeous Valley view acreage in the Slocan Va
lley.This property is a 4 acre unzoned parcel, with 2 water lic' and has a year round creek running through it. And in my opinion the most beautiful Valley views. Peek a boo river views and epic Valhalla and surrounding Valley mountain views.Property offers privacy
, an entertaining firepit/perennial garden area, orchard, stocked pond, level lawns, rockery gardens and walls and creekside bath area. To top it all off a huge 5 year old 45x60 timber frame shop. The shop has power and the start to a 1+ bedroom mezzanine suite.The
 home is 13 years old, just over 3000sqft, 3bds/3baths, with a fully finished basement and 2 bedroom 1 bath loft area.Home is finished with hardwood and granite flooring, infloor radiant heat, 400sqft concrete patio, timber accents throughout plus has floor to ceil
ing windows and epic views. Cedar board and batton siding and steel roof complete this modern mountain home.At the end of our driveway leads to endless backcountry and is just across the highway from Slocan City, the lake and Valhallas.Our home and property offer a
ll the things on a Kootenay property wish list. Welcome to MountainVista.Youtube video available for virtual tour. Please contact to viewMLS# 2452029https://youtu.be/sVeuklCYGRw", 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': '
Laval / North Shore', 'date_posted': '2020-08-01T21:28:56.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '3', 'Bathrooms': '2.5', 'Size (sqft)': '3100'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/calgary/room-in-downtown-10
0-meters-walk-to-8-th-street-train-station/1515582655', 'price': '550', 'address': '909 7 Ave SW, Calgary, AB T2P, Canada', 'longitude': -114.0820723, 'latitude': 51.0467224, 'jurisdiction': 'alberta', 'visit': 0, 'full_description': 'Room available in downtown clo
se proximity to train station, bus stops,restaurants, superstore,safeway..Looking for male preferably students - Indian', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:32:29.
000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '1', 'Bathrooms': '1', 'Size (sqft)': '600'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/charlottetown-pei/farmhouse-12-acres-riverfront-rural-riverview-nb/1515582041', 'price':
 '0', 'address': '62 Duffy Rd, Lower Coverdale, NB E1J 1S3, Canada', 'longitude': -64.7194341, 'latitude': 46.0474854, 'jurisdiction': 'prince-edward-island', 'visit': 0, 'full_description': '12 ACRES, RIVERFRONT - 1.5 STOREY FARMHOUSE - NEEDS RESTORING OR BUILD YO
UR DREAM HOME.CLOSE TO RIVERVIEW, DOWNTOWN MONCTON, NB $179,900 MLS KAREN LYONS REMAX QUALITY REAL ESTATE 506-383-3140', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:29:34.0
00Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '4', 'Bathrooms': '1'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/edmonton/live-in-the-hamptons-private-yard-attached-garage-luxury-town/1515583159', 'price': '227900', 'address
': '5604 199 St NW Unit 46, Edmonton, AB T6M 2Z9, Canada', 'longitude': -113.665019, 'latitude': 53.4905859, 'jurisdiction': 'alberta', 'visit': 0, 'full_description': "White picket fences & adorably perfect yards give you a feeling of class & serenity. That's exac
tly why people move to the Hamptons! We invite you into this spacious, 2storey townhouse which gives you the affordable & care free lifestyle of well known Mosaic Parkland. Welcome guests through your perfectly landscaped, low maintenance yard w/ tons of curb appea
l. Being south facing ensures your flowers will grow & your home will have lots of natural light. Enter into the open concept floor plan perfect for entertaining. Relax in your living room highlighted by a wall to wall, split faced stone surround fireplace or maybe
 have some drinks around your spacious eat up island. The kitchen has all stainless steel appliances & a good sized pantry. There's a 2pc bath on the way up to the smartly designed open riser staircase. Upstairs you will find 2 bedrooms & a 4pc bath, plus the conve
nience of top floor laundry. All you need is an attached garage which this home has, spacious enough for two cars. It's all here!", 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01
T21:34:48.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '2', 'Bathrooms': '1.5', 'Size (sqft)': '911'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/city-of-toronto/fitzmaurice-dr-vaughan-6bdr-6bths/1515583201', 'price': '209
0000', 'address': 'Fitzmaurice Dr, Vaughan, ON L6A, Canada', 'longitude': -79.4667922, 'latitude': 43.8694096, 'jurisdiction': 'ontario', 'visit': 0, 'full_description': "Price: $2090000 / $6598/mo*Luxurious Custom Home In Upper West Side. Great Space Design 3 Leve
l With Approx. 5400 Sqft Of Living Space. 6 Bedrooms Rarely In The Community. Impeccably 2nd Fl Cathedral Ceiling Living Rm With Open Space Floors. 4 Bedrooms On 2nd Fl & 2 Bedrooms & Study Space On 3rd Fl. 10' Ceiling Main Fl. Master Bedroom Offers Sumptuous En-Su
ite And Large W/I Closet. Beautiful Interlocking Backyard & Garden. Modern Kitchen W/O To Garden. Rec & Gym, Large Storage In Bsm.Over 120K Upgrades And Finished Basement. Modern Kitchen With S/S Appliances, Lg Washer/Dryer. Marble Counter & Island. All Window Cove
rings, All Elf's. Custom Build Wine Racks In Basement Cold Room. Large Composite Wood Deck & Gazebo.For faster response, please use the contact form and provide a valid name and phone number and I will be in touch.For more information copy & paste this link into yo
ur web browser: https://www.hmemkt.com/UC127MWe have access to literally thousands of properties!Visit our website at https://www.hmemkt.com/newlistings Try out our property search tools and get immediate results.All payments are based on 20% down payment at 2.99%
down amortized over 30 on OAC.**Instant Approvals On Mortgage rates from as low as 2.79% APRListing Office: RIGHT AT HOME REALTY INC., BROKERAGE", 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_poste
d': '2020-08-01T21:35:01.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '6+', 'Bathrooms': '6+'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/charlottetown-pei/beautiful-3-unit-apt-bldg-for-sale-in-charlottetown/1508103209',
'price': '649000', 'address': '103 N River Rd, Charlottetown, PE C1A 3K5, Canada', 'longitude': -63.1403602, 'latitude': 46.2347623, 'jurisdiction': 'prince-edward-island', 'visit': 2239, 'full_description': "Attention Investors! A gem like this doesn't become avai
lable often. This very well maintained 3 unit, 3 story apartment building is in the historic neighbourhood of Brighton in Charlottetown, PEI. The building has: New Siding, New Roof, New Windows, New Cast Iron Boiler. Inside there are currently one 1 bedroom apt, on
e 2 bedroom apartment, one 3 bedroom apartment. There is the potential to add a studio apartment in the attic area. The rents are below market and current annual gross revenue is greater than $45,000 annually. What a fantastic place to live and have supplementary i
ncome from the other units. Please contact Ian Walker at Gold Key Realty for additional info. 902-314-1761.", 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-07-23T18:07:02.000Z', 'resi
dence_type': 'House', 'principal_characteristics': ({'Bedrooms': '6+', 'Bathrooms': '3'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/ottawa/immediate-occupancy-cottage-on-lac-barriere-lac-simon/1511889707', 'price': '160000', 'address': 'J0V 1E0, Canada'
, 'longitude': -75.03968250000001, 'latitude': 45.9065022, 'jurisdiction': 'ontario', 'visit': 1613, 'full_description': 'FOR SALE3 season cottage with right of passage to lake.Located in the great Lac Simon area, Chnville Qubec.45 minutes from Montebello and 45 mi
nutes from the Tremblant villageTwo bedroom with newly renovated bathroom.All laminate floors. White kitchen with white appliances.Property is 100 feet x 100 feet with a septic system that is less that 10 yo.Will start showing beginning or August- quick occupancy.R
eserve your bookings now.. if add is up, still available.Communicate by text please', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-07-13T12:09:37.000Z', 'residence_type': 'House', 'p
rincipal_characteristics': ({'Bedrooms': '2', 'Bathrooms': '1', 'Size (sqft)': '600'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/st-catharines/brand-new-four-bedroom-home-for-sale/1512199422', 'price': '534900', 'address': 'Smith Rd, Thorold, ON L3B 5N5
, Canada', 'longitude': -79.2291967, 'latitude': 43.0391843, 'jurisdiction': 'ontario', 'visit': 257, 'full_description': 'Brand new two storey, 4 bedroom home for sale in the beautiful Empire Legacy Communities Thorold ( 406 and Merritt Road)Over $20,000 in upgrad
es, you could not build this home today for the current asking priceGreat rental potential- Niagara college 5 minutes away and Brock University is only 10 minutes away. Larger basement windows added for future basement renovations.Available for immediate possession
.No front neighbours and no rear neighbours directly facing the home. Property grading to occur mid August to early SeptemberGreat location for commutersIf interested in viewing, please contact Kirstin at the phone number provided', 'title': 'Propriétaires en diffi
culté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-07-21T17:38:43.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '4', 'Bathrooms': '2.5', 'Size (sqft)': '1907'}, {})}, {'url': 'https://www.k
ijiji.ca/v-house-for-sale/sudbury/house-for-sale-in-cartier/1515582762', 'price': '80000', 'address': '96 Lansdowne St, Sudbury, Unorganized, North Part, ON P0M, Canada', 'longitude': -81.55661119999999, 'latitude': 46.7087578, 'jurisdiction': 'ontario', 'visit': 0
, 'full_description': 'Looking for a quick sell! House is located in Cartier Ontario in the heart of unlimited fishing and bear hunting opportunity! This is a three bedroom house with a bathroom, kitchen, and living room. Also has a 1.5 car garage with a living spa
ce on the second floor with a bedroom, washroom with jacuzzi, kitchen and living room. It’s more of a camp feel. House has well water, septic tank, oil furnace all up to date two years ago, and two fire places for optional wood heat in house and garage living space
. Upstairs could be rented.. Come with everything in the house. asking 80,000$ obo', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:32:53.000Z', 'residence_type': 'House', 'pr
incipal_characteristics': ({'Bedrooms': '4', 'Bathrooms': '2'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/edmonton/stunning-2-storey-in-crystallina-nera-schmidt-realty-group-inc/1515582925', 'price': '539900', 'address': '912 Crystallina Nera, Edmonton
T5L0L1 AB, Canada', 'longitude': -113.4621041, 'latitude': 53.64317510000001, 'jurisdiction': 'alberta', 'visit': 0, 'full_description': 'Welcome to 912 Crystallina Nera!More pics and info at www.912-crystallinaneraway.comMove-in ready in Crystallina Nera! This stu
nning 2500+ square foot Pacesetter Gabriel Plan checks all the boxes: cul-de-sac location with friendly neighbours, pie shaped landscaped lot with south facing backyard, steps away from the lake and trails and a spacious, bright open concept layout! Grand custom ki
tchen with hood fan, gas range, solid wood cabinets, granite, walk through pantry and seating for 4 around the island. Entertaining is a breeze with large sunny dining room including full windows and coffered ceiling. The living room is spacious and offers a cozy g
as fireplace and more floor to ceiling windows! Upstairs is sure to impress with a luxurious master suite including double sided gas fireplace, custom walk-in closet and large windows overlooking the backyard. The massive ensuite features vaulted ceilings, chandeli
er, soaker tub, separate shower with body jets and custom rock floor, double sinks, makeup vanity and water closet. Two more bedrooms, a full bath and bonus room with soaring vaulted ceilings complete this lovely home!To view all of our available listings, or to fi
nd out what YOUR home is worth, visit our website at:www.SchmidtRealtyGroup.com', 'title': 'Propriétaires en difficulté financière, REPRISES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T21:33:50.000Z', 'residence_type': 'House', 'princ
ipal_characteristics': ({'Bedrooms': '3', 'Bathrooms': '2.5', 'Size (sqft)': '2588'}, {})}, {'url': 'https://www.kijiji.ca/v-house-for-sale/muskoka/cottage-for-sale-at-shamrock-bay-resort/1507018760', 'price': '58500', 'address': 'Shamrock Marina Rd, P0E 1N0, Sever
n Bridge, ON', 'longitude': -79.35673, 'latitude': 44.774803, 'jurisdiction': 'ontario', 'visit': 8554, 'full_description': "Welcome to Shamrock Bay Resort!The perfect cottage getaway less than 1.5 hours from Toronto right in the heart of Muskoka Cottage country. I
t is located just South of Gravenhurst on 1082 Shamrock Marina Rd, Unit 246.For sale is a 2 Bedroom Northlander Acorn 2015 park model home. 432 SQ feet with an upgraded 300 SQ feet deck with Black vinyl railing. It is fully furnished with a 3 piece washroom, master
 bedroom, Double/Single bunk bed in the 2nd bedroom, kitchen, dining area and a double pull out couch. Easily sleeps 5+ people.There is a furnace and AC in the unit. All patio furniture, BBQ, Fire pit, lawn chairs are included.The resort features an ample list of a
ctivities great for families with children of all ages.-Professional basketball court-Playground-2 Heated Pools (kids knee deep pool + adult depth pool)-Boat slip/Boat Storage-Boat lunch-Club house with free Wifi, Kidz club-Fishing on trent river waterway and Sparr
ow lake-Free Children's Activities (Christmas in July, Halloween in August, face painting, horse buggy rides)-Adult Activities (potluck dinner, live music concerts,-Long weekend Incredible Firework displays-Free Kayak and Canoe rentals.-Laundramat serviceMany more!
The Resort is open May 1 to October 31 with all the grounds maintenance, most activities, water and hydro, property taxes and friendly staff to help with any inquires included in the resort fees. for 2020 the fees are 6751.76The best part about this is the easy ent
ry into cottage ownership at a fraction of the price. Headache free, drive up, unpack, start up the BBQ and enjoy the great outdoors. You will not be dissapointed!Contact via email or phone for any showings.", 'title': 'Propriétaires en difficulté financière, REPRI
SES, SUCCESSION...', 'city': 'Laval / North Shore', 'date_posted': '2020-08-01T00:24:54.000Z', 'residence_type': 'House', 'principal_characteristics': ({'Bedrooms': '2', 'Bathrooms': '1'}, {})}]"""

import json 


b =  json.loads(a.replace(")","").replace("(","").replace("\n",""))